export const timelineDatas = [
  {
    year: "2021 - 2022",
    title: "Developpeur Front End",
    place: "Openclassrooms",
    infos: "",
    type: "degree",
  },
  {
    year: "2020 - 2021",
    title: "Gestionnaire de stocks",
    place: "Capel Paris",
    infos: "Gestion des stocks, préparation de commandes, livraisons",
    type: "job",
  },
  {
    year: "2019",
    title: "Conseiller de ventes",
    place: "Groupe GR",
    infos:
      "Promotion et vente de proximité pour un nouveau produit Philip Morris INternational.",
    type: "job",
  },
  {
    year: "2017 - 2019",
    title: "Employé commercial",
    place: "Carrefour Market Valence",
    infos:
      "Encaissement, mise en rayon, gestion de stocks, commandes rayon fruits et légumes.",
    type: "job",
  },
  {
    year: "2015",
    title: "Vendeur en boulangerie",
    place: "Les Vieilles Poutres",
    infos: "Vente de boulangeries/patisseries",
    type: "job",
  },
  {
    year: "2013-2014",
    title: "E.N.S.A. Limoges",
    place: "Ecole Nationale Superieur d'Art de Limoges",
    infos: "1ère année",
    type: "school",
  },
  {
    year: "2012-2013",
    title: "Préparation Artistique",
    place: "Prep'art paris",
    infos: "Dessin, design",
    type: "school",
  },
  {
    year: "2012",
    title: "Employé commercial",
    place: "Carrefour Market Montesson",
    infos: "Mise en rayon.",
    type: "job",
  },
  {
    year: "2012",
    title: "Thangs",
    place: "création autoentreprise design graphique",
    infos: "Logos, affiche, mise en page",
    type: "school",
  },
  {
    year: "2011",
    title: "Mécanicien poids lourds",
    place: "C.S.O.",
    infos: "Entretient mécanique et électrique d'autobus",
    type: "job",
  },
  {
    year: "2010",
    title: "B.T.S M.A.I",
    fullName: "B.T.S Mécanique et Automatismes Industriels",
    place: "Lycée Léonarde de Vinci Saint-Germain-en-laye",
    infos: "",
    type: "degree",
  },
  {
    year: "2009 & 2010",
    title: "Employé service Espace vert",
    place: "Ville de Montesson",
    infos: "Entretient des espaces verts",
    type: "job",
  },
  {
    year: "2008",
    title: "Bac S.T.I",
    fullName: "Baccalauréat S.T.I Génie Electrotechnique",
    place: "Lycée Léonarde de Vinci Saint-Germain-en-laye",
    infos: "Electicité, Mécanique et Automatisme industriels",
    type: "degree",
  },
];
